hydra:
  job_logging:
    root:
      handlers: [console]
      level: INFO
      formatter: simple
    formatters:
      simple:
        format: "[%(asctime)s][%(filename)s][%(levelname)s] - %(message)s"
        datefmt: "%d-%m-%Y %H:%M:%S"
  run:
    dir: .
  output_subdir: null

settings:
  seed: 42
  runs: 1
  verbose: True

paths:
  source: data
  output: output

data:
  type: ML # ML or DL
  extension: csv
  separator: ","
  target: Label

experiment:
  train_size: 0.8
  test_size: 0.2
  val_size: 0.1

