hydra:
  job_logging:
    root:
      handlers: [console]
      level: INFO
      formatter: simple
    formatters:
      simple:
        format: "[%(asctime)s][%(filename)s][%(levelname)s] - %(message)s"
        datefmt: "%d-%m-%Y %H:%M:%S"
  run:
    dir: .
  output_subdir: null

settings:
  seed: 42
  runs: 1
  verbose: True

paths:
  source: data
  output: output

data:
  type: ML # ML or DL
  extension: csv
  separator: ","
  target: Label
  id: Id

scaling:
  type: Standard # Standard, MinMax, Robust, MaxAbs, Quantile, Power, Normalizer
  target: Label

model:
  name: RandomForest # RandomForest, SVC, LogisticRegression, MLP, XGBoost, LightGBM, CatBoost

optuna:
  n_trials: 50

experiment:
  train_size: 0.7
  test_size: 0.3
  val_size: 0.2
  folds: 10


