hydra:
  job_logging:
    root:
      handlers: [console]
      level: INFO
      formatter: simple
    formatters:
      simple:
        format: "[%(asctime)s][%(filename)s][%(levelname)s] - %(message)s"
        datefmt: "%d-%m-%Y %H:%M:%S"
  run:
    dir: .
  output_subdir: null

settings:
  seed: 42
  runs: 1
  verbose: False
  debug: False
  results_analysis: False
  type: DL # ML or DL

paths:
  source: data
  output: output

data:
  #dataset: ['ConvNeXtSmall', 'EfficientNetV2S', 'InceptionResNetV2', 'InceptionV3', 'All', 'InAir', 'OnPaper', 'InAirOnPaper']
  dataset: ['ConvNeXtSmall', 'InAir'] # All, InAir, OnPaper, InAirOnPaper , ConvNeXtSmall, EfficientNetV2S, InceptionResNetV2
  extension: csv
  separator: ","
  target: Label
  id: Id
  id_index: Id_index

scaling:
  type: Robust

model:
  name: XGB # RandomForest, SVC, DecisionTree, XGB

optuna:
  n_trials: 2

experiment:
  train_size: 0.7 # 0.5 for stacking Classification
  test_size: 0.3 # 0.5 for stacking Classification
  test_size_final: 0.2
  val_size: 0.2
  folds: 5
  calibration: True
  calibration_method: isotonic
  calibration_cv: 5
  stacking_method: Bayesian # Bayesian, Classification, MajorityVote, WeightedMajorityVote
  stacking_model: LogisticRegression # MLP, LogisticRegression

bayesian_net:
  algorithm: HillClimb  # PC , HillClimb, GES, Tree
  score_metric: bic  # Scoring metric for final evaluation: k2, bdeu, bds, bic, aic
  prior_type: K2  # Prior type for parameter learning: K2 or BDeu
  use_parents: true
  max_parents: 3

  # PC-specific parameters
  ci_test: mutual_info_test   # Options: pearsonr, chi_square, g_sq, fisher_exact
  significance_level: 0.3  # Default: 0.05, Range: 0.01-0.1
  max_cond_vars: 10  # Maximum size of conditioning set
  stable: true  # Use stable version of PC
  complete_dag_search: true  # Whether to search complete DAG space

  # Verbosity settings
  verbose: false
  show_progress: false

  n_jobs: 1
  cache_size: 1000
  early_stopping_steps: 5
  score_delta_threshold: 1e-4