hydra:
  job_logging:
    root:
      handlers: [console]
      level: INFO
      formatter: simple
    formatters:
      simple:
        format: "[%(asctime)s][%(filename)s][%(levelname)s] - %(message)s"
        datefmt: "%d-%m-%Y %H:%M:%S"
  run:
    dir: .
  output_subdir: null

settings:
  seed: 42
  runs: 1
  verbose: False
  debug: False

paths:
  source: data
  output: output

data:
  type: ML # ML or DL or ML_orig for cleaning the statistical data
  dataset: InAirOnPaper # All, InAir, OnPaper, InAirOnPaper , CNN1, CNN2, ...
  type_2: None # ML or DL or None # DA USARE IN CASO DI COMBINING DATASET
  dataset2: None # Dataset da combinare con il primo
  extension: csv
  separator: ","
  target: Label
  id: Id
  id_index: Id_index

scaling:
  type: Standard # Standard, MinMax, Robust, MaxAbs, Quantile, Power, Normalizer

model:
  name: DecisionTree # RandomForest, CatBoost, SVC, DecisionTree, XGB

optuna:
  n_trials: 5

experiment:
  train_size: 0.5
  test_size: 0.5
  test_size_final: 0.2
  val_size: 0.2
  folds: 5
  calibration: True # True or False
  calibration_method: isotonic # isotonic or sigmoid
  calibration_cv: 5
  stacking_method: Bayesian # Bayesian, Classification, MajorityVote, WeightedMajorityVote
  stacking_model: LogisticRegression # MLP, LogisticRegression


bayesian_net:
  algorithm: HillClimb # HillClimb, Exhaustive, PC, TreeSearch
  prior_type: BDeu # BDeu, K2 These alternatives specify the type of prior distribution to use for parameter estimation
  max_parents: 3 #
  use_parents: False
  verbose: False


